### ISSUE TITLE
Fix Stack Not Affecting Most Items With A Max Stack Of 1

### ISSUE THREAD

**Issue by anselhelm** [OmerBenGera/WildStacker#60]
Hi,

This is the part of the configuration I am referring to:

  When fix-stack is disabled, items with a max-stack of 1 will be added to inventories
  with a max-stack size of 64. If a player picks up 80 picks, he will get 64 + 16, instead
  of 80 different items.
  fix-stack: true

Unless I'm misunderstanding this, it should allow all items to be stacked, such as flint/steel, beds, minecarts etc. However, even with this enabled, such items remain unstackable.

I'm unsure if it's related to this setting, but I believe the setting is also attempting to amend the max stack size for other items, such as ender pearls (standard 16 stack limit). However, it seems to only work intermittently.

**Comment by OmerBenGera** [comment]
When this field is enabled, it will make items to not be oversized. This means that when you pick up a stacked item of pickaxes, for example, you will receive multiple items instead of one item that has amount larger than the maximum stack size (1 in this example).
It has nothing to do with items stacking or not on ground, it only affects how you receive these items to your inventory.
